"""
Face embedding service.
Responsible only for handling embedding vectors generated by face detection.
"""

import logging
from typing import List, Optional

import cv2
import numpy as np

logger = logging.getLogger(__name__)


class FaceEmbeddingService:
    """
    Handles face embedding vectors.

    InsightFace embedding is generated during face detection.
    This service does NOT create another FaceAnalysis model and
    does NOT run face detection a second time.
    """

    def __init__(self):
        self._embedding_dim = 512

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @property
    def embedding_dim(self) -> int:
        """Dimensionality of generated embedding vectors."""
        return self._embedding_dim

    def get_embedding(
        self,
        embedding: Optional[List[float]],
    ) -> Optional[List[float]]:
        """
        Return the embedding already generated by InsightFace.

        Args:
            embedding: Embedding captured during face detection.

        Returns:
            Normalized embedding or None.
        """

        if embedding is None:
            logger.warning("No InsightFace embedding available")
            return None

        if len(embedding) != self._embedding_dim:
            logger.warning(
                "Unexpected embedding dimension: %d (expected %d)",
                len(embedding),
                self._embedding_dim,
            )
            return None

        return self._normalize(embedding)

    # ------------------------------------------------------------------
    # HOG fallback
    # ------------------------------------------------------------------

    def generate_hog_embedding(
        self,
        image: np.ndarray,
    ) -> Optional[List[float]]:
        """
        Generate a HOG-based fallback embedding.

        This is only a demonstration fallback.
        It is NOT suitable for production face recognition.
        """

        try:
            resized = cv2.resize(image, (64, 64))
            gray = cv2.cvtColor(
                resized,
                cv2.COLOR_BGR2GRAY,
            )

            hog = cv2.HOGDescriptor(
                _winSize=(64, 64),
                _blockSize=(16, 16),
                _blockStride=(8, 8),
                _cellSize=(8, 8),
                _nbins=9,
            )

            descriptor = hog.compute(gray).flatten()

            if len(descriptor) >= self._embedding_dim:
                embedding = descriptor[
                    :self._embedding_dim
                ].tolist()
            else:
                embedding = np.pad(
                    descriptor,
                    (
                        0,
                        self._embedding_dim - len(descriptor),
                    ),
                ).tolist()

            return self._normalize(embedding)

        except Exception as exc:
            logger.error(
                "HOG embedding failed: %s",
                exc,
            )
            return None

    # ------------------------------------------------------------------
    # Normalization
    # ------------------------------------------------------------------

    @staticmethod
    def _normalize(
        embedding: List[float],
    ) -> List[float]:
        """L2-normalize an embedding vector."""

        arr = np.array(
            embedding,
            dtype=np.float32,
        )

        norm = np.linalg.norm(arr)

        if norm == 0.0:
            return embedding

        return (
            arr / norm
        ).tolist()